# Generated by TestIn01 Framework Export
# 2025-11-20T06:23:44.036125500+00:00

from playwright.sync_api import Page

class Aries:
    def __init__(self, page: Page):
        self.page = page

    
    
    
    
    
    @property
    def container(self):
        return self.page.locator("//div[@class='bg-light dark:bg-transparent min-vh-100 d-flex flex-row align-items-center']")

    
    
    
    
    
    @property
    def form(self):
        return self.page.locator("//form[@class='ng-untouched ng-pristine ng-invalid']")

    
    
    
    
    
    @property
    def loginheading(self):
        return self.page.locator("//h1[normalize-space(.)='Login']")

    
    
    
    
    
    @property
    def signintoyouraccountpara31(self):
        return self.page.locator("//p[@class='text-body-secondary']")

    
    
    
    
    
    @property
    def span(self):
        return self.page.locator("(//span)[1]")

    
    
    
    
    
    @property
    def usernameinput(self):
        return self.page.locator("username")

    
    
    
    
    
    @property
    def passwordpasswordinput(self):
        return self.page.locator("password")

    
    
    
    
    
    @property
    def loginbutton(self):
        return self.page.locator("(//button)[1]")

    
    
    
    
    
    @property
    def forgotpasswordbutton(self):
        return self.page.locator("(//button)[2]")

    
    # Navigation methods
    def navigate_to(self, url: str):
        """Navigate to the page"""
        self.page.goto(url)
    
    def wait_for_page_load(self):
        """Wait for page to load"""
        self.page.wait_for_load_state("networkidle") 